# Generated by Django 4.2.6 on 2024-10-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
