# Generated by Django 4.2.6 on 2025-01-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project that the mentor is leading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_leads', to='projects.project'),
        ),
    ]
