# Generated by Django 5.1.4 on 2025-01-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project that the mentor is leading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_leads', to='projects.project'),
        ),
    ]
