# Generated by Django 4.2.6 on 2025-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_mentor_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='season',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='season',
            field=models.TextField(default='1'),
        ),
    ]
