# Generated by Django 4.2.6 on 2025-01-15 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_mentee_season_alter_mentor_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='The rank given by the mentor to the mentee for this project.', validators=[django.core.validators.MinValueValidator(1)])),
                ('mentee', models.ForeignKey(help_text='The mentee who is ranked by the mentor.', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='projects.mentee')),
                ('mentor', models.ForeignKey(help_text='The mentor who ranked the mentee.', on_delete=django.db.models.deletion.CASCADE, related_name='ranklists', to='projects.mentor')),
                ('project', models.ForeignKey(help_text='The project associated with the ranking.', on_delete=django.db.models.deletion.CASCADE, related_name='ranklists', to='projects.project')),
            ],
            options={
                'verbose_name': 'Rank List',
                'verbose_name_plural': 'Rank Lists',
                'ordering': ['rank'],
                'unique_together': {('mentor', 'mentee', 'project')},
            },
        ),
    ]
