# Generated by Django 4.2.6 on 2024-10-16 18:43

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_mentee_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image_link',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_to),
        ),
    ]
