# Generated by Django 4.2.6 on 2024-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_banner_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
