# Generated by Django 4.2.6 on 2025-02-26 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_ranklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ranklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ranklist',
            name='preference',
            field=models.ForeignKey(default=1, help_text='The prefernce of that mentee', on_delete=django.db.models.deletion.CASCADE, related_name='prefer', to='projects.menteepreference'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ranklist',
            unique_together={('mentor', 'mentee', 'project', 'preference')},
        ),
    ]
