# Generated by Django 4.2.6 on 2025-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_ranklist_unique_together_ranklist_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranklist',
            name='preference',
            field=models.PositiveIntegerField(help_text='The preference given of mentee for this project.'),
        ),
    ]
