# Generated by Django 4.2.6 on 2025-03-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_ranklist_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='project',
        ),
        migrations.AddField(
            model_name='mentor',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='The project that the mentor is leading.', related_name='mentors', to='projects.project'),
        ),
    ]
