# Generated by Django 4.2.6 on 2025-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_mentor_project_mentor_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='general_category',
            field=models.CharField(choices=[('ML', 'ML'), ('Development', 'Development'), ('Blockchain', 'Blockchain'), ('CP', 'CP'), ('Others', 'Others')], default='Others', max_length=255),
        ),
    ]
