# Generated by Django 4.2.6 on 2025-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_general_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='weekly_meets',
            field=models.BigIntegerField(default=0),
        ),
    ]
