# Generated by Django 4.2.6 on 2025-04-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_weekly_meets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='weekly_meets',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
