# Generated by Django 4.2.6 on 2025-04-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_weekly_meets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menteepreference',
            unique_together={('mentee', 'preference'), ('mentee', 'project')},
        ),
    ]
