# Generated by Django 4.2.6 on 2025-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_menteepreference_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='general_category',
            field=models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('Development', 'Development'), ('Blockchain', 'Blockchain'), ('Competitive Programming', 'Competitive Programming'), ('Others', 'Others')], default='Others', max_length=255),
        ),
    ]
