# Generated by Django 4.2.6 on 2026-03-30 — extended with data deduplication for RankList

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def deduplicate_ranklist(apps, schema_editor):
    """
    Old RankList had unique_together = (mentor, mentee, project, preference).
    New unique_together = (project, mentee).
    
    Deduplicate by keeping only the entry with the lowest rank
    for each (project, mentee) pair.
    """
    RankList = apps.get_model('projects', 'RankList')
    db_alias = schema_editor.connection.alias

    seen = set()
    for entry in RankList.objects.using(db_alias).order_by('project_id', 'mentee_id', 'rank'):
        key = (entry.project_id, entry.mentee_id)
        if key in seen:
            entry.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_unique_username_role_and_more'),
        ('domains', '0001_initial'),
        ('projects', '0012_alter_project_general_category'),
    ]

    operations = [
        # Remove old unique_together on ranklist first
        migrations.AlterUniqueTogether(
            name='ranklist',
            unique_together=set(),
        ),
        # Add domain FK to Mentee, Mentor, Project (all nullable for existing data)
        migrations.AddField(
            model_name='mentee',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='domains.domain'),
        ),
        # Change Mentee.user from OneToOne to ForeignKey
        migrations.AlterField(
            model_name='mentee',
            name='user',
            field=models.ForeignKey(help_text='The user profile corresponding to the mentee.', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        # Update Mentor.projects related name
        migrations.AlterField(
            model_name='mentor',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects that this mentor is leading in this domain.', related_name='mentors', to='projects.project'),
        ),
        # Change Mentor.user from OneToOne to ForeignKey
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(help_text='The user profile corresponding to the mentor.', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        # Update Project category choices
        migrations.AlterField(
            model_name='project',
            name='general_category',
            field=models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('Development', 'Development'), ('Blockchain', 'Blockchain'), ('Competitive Programming', 'Competitive Programming'), ('Quant / Finance', 'Quant / Finance'), ('Robotics / Hardware', 'Robotics / Hardware'), ('Others', 'Others')], default='Others', max_length=255),
        ),
        # Update RankList FKs with better help text
        migrations.AlterField(
            model_name='ranklist',
            name='mentee',
            field=models.ForeignKey(help_text='The mentee being ranked.', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='projects.mentee'),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='preference',
            field=models.PositiveIntegerField(help_text="The mentee's own preference number for this project."),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='project',
            field=models.ForeignKey(help_text='The project this ranking belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ranklists', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='rank',
            field=models.PositiveIntegerField(help_text='Rank given to this mentee for this project (1 = highest preference).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        # Deduplicate ranklist BEFORE adding new unique_together
        migrations.RunPython(
            deduplicate_ranklist,
            reverse_code=migrations.RunPython.noop,
        ),
        # Add unique_together constraints
        migrations.AlterUniqueTogether(
            name='mentee',
            unique_together={('user', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together={('user', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='ranklist',
            unique_together={('project', 'mentee')},
        ),
        # Finally, remove the mentor FK from RankList
        migrations.RemoveField(
            model_name='ranklist',
            name='mentor',
        ),
    ]
