# Generated by Django 4.2.6 on 2026-03-30 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import domains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Short identifier, e.g. 'soc', 'soq'", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Full name, e.g. 'Summer of Code'", max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=domains.models.upload_domain_cover)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display ordering (lower = first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DomainMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee'), ('manager', 'Manager')], max_length=10)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this membership has been approved by a domain manager')),
                ('domain', models.ForeignKey(blank=True, help_text='Null means platform-level manager with access to all domains', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='domains.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined'],
                'unique_together': {('user', 'domain', 'role')},
            },
        ),
    ]
