# Generated by Django 4.2.6 on 2026-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mentee_reg_open',
            field=models.BooleanField(default=False, help_text='Open for mentees to self-register'),
        ),
        migrations.AddField(
            model_name='domain',
            name='mentor_reg_open',
            field=models.BooleanField(default=False, help_text='Open for mentors to self-register (pending approval)'),
        ),
    ]
