version: "3.8"

services:
  backend:
    build:
      context: ./socbackend
      dockerfile: Dockerfile
    container_name: soc-backend
    restart: always
    env_file:
      - ./socbackend/.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    networks:
      - soc_network

  frontend:
    build:
      context: ./socfrontend
      dockerfile: Dockerfile
    container_name: soc-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - soc_network

networks:
  soc_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
