# Generated by Django 4.2.6 on 2025-01-02 14:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], default='mentee', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(help_text='Required. 9 characters or fewer.', max_length=9, validators=[accounts.models.validate_roll_number], verbose_name='roll number'),
        ),
    ]
