# Generated by Django 4.2.6 on 2026-03-30 — extended with data deduplication step

from django.db import migrations, models


def deduplicate_usernames(apps, schema_editor):
    """
    Before adding unique=True on username, merge duplicate CustomUser rows
    that exist because the old schema used (username, role) as the compound key.
    
    Strategy: for each set of dupes, keep the one with the lowest id (oldest)
    and delete the rest. We cannot transfer FKs inside a migration safely, but
    the seed_soc_domain command handles the FK transfer afterwards.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    db_alias = schema_editor.connection.alias

    # Find all duplicate usernames
    from django.db.models import Count
    dupes = (
        CustomUser.objects.using(db_alias)
        .values('username')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for dupe in dupes:
        username = dupe['username']
        users = list(
            CustomUser.objects.using(db_alias)
            .filter(username=username)
            .order_by('id')
        )
        canonical = users[0]
        for extra in users[1:]:
            # Just delete the duplicate — FK transfer done by seed_soc_domain command
            extra.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_department'),
    ]

    operations = [
        # 1. Remove the old constraint first
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_username_role',
        ),
        # 2. Remove the role field
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        # 3. Deduplicate usernames BEFORE adding unique constraint
        migrations.RunPython(
            deduplicate_usernames,
            reverse_code=migrations.RunPython.noop,
        ),
        # 4. Now it's safe to add unique=True
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year'), ('M.Tech', 'M.Tech'), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], max_length=100),
        ),
    ]
